get_all_orders = 'GET all orders'
get_all_orders_in_queue = 'GET all orders in queue'
delete_outstanding_request = 'DELETE outstanding request'
get_order_by_id = 'GET order by ID'
patch_order_by_id_close = 'PATCH(Close) order by ID for user {0}({1})'
patch_order_by_id_accept = 'PATCH(Accept) order by ID for user {0}({1})'
get_all_orders_by_user = 'GET all orders for one User'
get_booking = 'GET(Book) one particular document by ID'
