get_all_orders = 'GET all orders'
get_all_orders_in_queue = 'GET all orders in queue'
delete_outstanding_request = 'DELETE outstanding request'
get_order_by_id = 'GET order by ID'
patch_order_by_id = 'PATCH(Check out) order by ID'
get_all_orders_by_user = 'GET all orders for one User'
get_booking = 'GET(Book) one particular document by ID'
