get_all_orders = 'GET all orders by user ({0}:{1})'
get_all_orders_in_queue = 'GET all orders in queue by user ({0}:{1})'
delete_outstanding_request = 'DELETE outstanding request by user ({0}:{1})'
get_order_by_id = 'GET order by ID by user ({0}:{1})'
patch_order_by_id = 'PATCH(Accept/Close) order by ID by user ({0}:{1})'
get_all_orders_by_user = 'GET all orders by user ({0}:{1})'
get_booking = 'GET(Book) one particular document by ID by user ({0}:{1})'
