INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (98, ' Amir');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (100, ' Behrouz H.');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (96, ' Bijan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (528, ' Calif.)');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (307, ' Chandrakant Chouby');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (435, ' Chekhovskiĭ raĭon');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (94, ' Elham Akhond Zadeh');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (359, ' III');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (105, ' PhD');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (306, ' Ravikant Choubey');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (436, ' Russia)');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (455, 'A. B. Pippard');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (220, 'A. Fijany');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (69, 'A. M. Pitts');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (392, 'A.P.Godse');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (314, 'A.R. Vasishtha');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (540, 'Abbey Deitel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (265, 'Abraham Ginzburg');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (241, 'Adam G. Koch');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (250, 'Adrian Reed Smith');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (124, 'Ajay Ohri');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (36, 'Ajit Narayanan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (646, 'Al Kelley');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (355, 'Alain Robert');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (243, 'Alan T. Norman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (274, 'Alan Weinstein');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (221, 'Alan Winfield');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (256, 'Alan Wright');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (97, 'Albadvi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (463, 'Albert Einstein');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (59, 'Albert G. Holzman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (122, 'Alberto Boschetti');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (121, 'Aleš Žiberna');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (117, 'Alexey Grigorev');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (182, 'Allan Ramsay');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (13, 'Allen B. Tucker');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (38, 'Allen Kent');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (701, 'Allen Wyatt');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (31, 'American Mathematical Society');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (235, 'Amit Bhardwaj');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (158, 'Amit Konar');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (603, 'Andreas Vogel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (45, 'Andrej Ščedrov');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (8, 'Andrew Butterfield');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (504, 'Andrew Herman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (240, 'Andrew Johnson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (106, 'Andrew Morgan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (521, 'Anne B. Keating');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (17, 'Anne Kerr');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (391, 'Anoop Gupta');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (239, 'Anthony Heston');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (26, 'Anthony Ralston');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (107, 'Antoine Amend');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (120, 'Anuška Ferligoj');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (186, 'Appin Knowledge Solutions');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (185, 'Appuu Kuttan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (664, 'Ashok Arora');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (640, 'Ashok Kamthane');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (289, 'Augustus De Morgan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (652, 'Avinash Bansal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (207, 'B. Z. Sandler');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (587, 'Balagurusamy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (624, 'Barry A. Burd');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (586, 'Barry Burd');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (584, 'Barry J. Holmes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (407, 'Barry Wilkinson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (317, 'Bartholomew Price');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (418, 'Behrooz Parhami');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (40, 'Behrouz A. Forouzan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (157, 'Ben Coppin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (424, 'Ben Everard');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (73, 'Benjamin S. Baumer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (465, 'Bernard F. Schutz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (372, 'Bertrand Dupouy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (607, 'Bhave');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (139, 'Bikramaditya Singhal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (152, 'Blay Whitby');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (580, 'Borja Sotomayor');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (24, 'Branislav Rovan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (610, 'Brett Spell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (698, 'Brian Bramer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (79, 'Brian Steele');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (628, 'Brian W. Kernighan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (335, 'Bruce Cooperstein');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (291, 'Bruce H. Edwards');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (297, 'Bruce van Brunt');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (192, 'Bruno Siciliano');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (575, 'Buyya');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (625, 'C. Xavier');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (343, 'C. Y. Hsiung');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (309, 'C.H.Jr. Edwards');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (361, 'Carl D. Meyer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (204, 'Carl F. Ruoff');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (9, 'Carl French');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (519, 'Carol Lipson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (632, 'Carol Ziegler');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (384, 'Caxton C. Foster');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (457, 'Cécile DeWitt-Morette');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (284, 'Centre for Economic Policy Research (Great Britain)');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (702, 'Charles A. Kapps');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (427, 'Charles Riborg Mann');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (645, 'Chhabra');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (576, 'Chip Weems');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (253, 'Chris Dannen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (52, 'Chris Doran');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (526, 'Christian Harder');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (252, 'Christian Newman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (177, 'Christopher Drummond');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (160, 'Christopher Thornton');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (655, 'Clovis L. Tondo');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (534, 'Codry Williams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (57, 'Committee on the Fundamentals of Computer Science: Challenges and Opportunities');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (56, 'Computer Science and Telecommunications Board');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (706, 'Craig Steiner');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (491, 'Cynthia L. Selfe');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (656, 'D Ravichandran');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (415, 'D. P. Agrawal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (393, 'D.A.Godse');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (654, 'D.S. Rajendra Prasad');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (310, 'Dale E. Varberg');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (245, 'Dale Michelson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (383, 'Daniel Page');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (585, 'Daniel T. Joyce');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (74, 'Daniel T. Kaplan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (591, 'Danny Poo');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (619, 'Dario Laverde');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (523, 'Dave Raggett');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (374, 'David A. Patterson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (368, 'David B. Damiano');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (358, 'David Bau');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (294, 'David Berlinski');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (321, 'David Bock');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (672, 'David C. Alexander');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (389, 'David E. Culler');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (34, 'David Ferro');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (483, 'David G. Andrews');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (108, 'David George');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (475, 'David Halliday');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (397, 'David Harris');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (27, 'David Hemmendinger');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (616, 'David Holmes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (622, 'David J. Barnes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (334, 'David Kincaid');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (254, 'David LEE Kuo Chuen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (429, 'David R. Lide');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (485, 'David W. Schumann');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (267, 'David Warren Cohen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (612, 'DEBASIS SAMANTA');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (617, 'DEBASISH JANA');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (510, 'Deborah Morley');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (524, 'Debra Cameron');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (292, 'Dennis G. Zill');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (629, 'Dennis Ritchie');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (281, 'Derek A. Kelly');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (350, 'Derek J S Robinson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (362, 'Derek John Scott Robinson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (592, 'Derek Kiong');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (144, 'Derek Partridge');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (408, 'Desző Sima');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (248, 'Devin Williams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (331, 'Dexter J. Booth');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (165, 'Deyi Li');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (495, 'Dieter Fensel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (87, 'Ding-Geng Chen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (55, 'Division on Engineering and Physical Sciences');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (667, 'Don Brumm');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (589, 'Donald Bales');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (530, 'Dori Smith');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (21, 'Doug Rose');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (313, 'Douglas Downing');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (623, 'Douglas Lea');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (210, 'Douglas R. Malcolm');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (364, 'E. Sernesi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (439, 'E.M. Lifshitz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (270, 'Earl William Swokowski');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (420, 'Eben Upton');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (588, 'Edward Currie');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (582, 'Edward Hill');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (11, 'Edwin D. Reilly');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (311, 'Edwin Joseph Purcell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (170, 'Elizabeth A. Wilson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (492, 'Elizabeth Castro');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (129, 'EMC Education Services');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (527, 'Environmental Systems Research Institute (Redlands');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (648, 'Enzo Marinari');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (658, 'Ernest C. Ackermann');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (486, 'Esther Thorson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (150, 'Eugene Charniak');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (446, 'Evgeniĭ Mikhaĭlovich Lifshit︠s︡');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (99, 'Far');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (76, 'Field Cady');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (41, 'Firouz Mosharraf');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (82, 'Foster Provost');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (64, 'Françoise Fogelman-Soulié');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (511, 'Fred Edmund Jandt');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (366, 'Fred Szabo');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (181, 'Frederick J. Crosson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (535, 'Fritz J. Erickson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (351, 'Fuzhen Zhang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (403, 'G. Boulaye');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (63, 'G. Shankar Rao');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (344, 'G. Y. Mao');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (175, 'Gabriel Hallevy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (490, 'Gail E. Hawisher');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (533, 'Gail Junion-Metz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (336, 'Gareth Williams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (116, 'Garrett Grolemund');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (676, 'Gary Elfring');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (595, 'Gary Shelly');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (231, 'Gaurav Suhas Sukhatme');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (184, 'George A. Bekey');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (218, 'George Bekey');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (153, 'George F. Luger');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (428, 'George Ransom Twiss');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (327, 'Georgi E. Shilov');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (602, 'Gerald Brose');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (442, 'Gerald D. Mahan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (285, 'Gerald L. Bradley');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (371, 'Gérard Blanchet');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (16, 'Gerard Ekembe Ngondi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (262, 'Gerry Marrs');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (229, 'Gibilisco');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (263, 'Gilbert Strang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (618, 'Giulio Ferrari');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (196, 'Giuseppe Carbone');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (211, 'Giuseppe Oriolo');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (37, 'Gordon J. Pace');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (398, 'Govindarajalu');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (90, 'Grace Yi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (620, 'Graham Hall');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (128, 'Graham J. Williams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (414, 'Graham R Wilson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (33, 'Greg Anderson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (382, 'Gurindar Sohi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (115, 'Hadley Wickham');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (283, 'Hanna Halaburda');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (119, 'Hans-Hermann Bock');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (91, 'Hao Yu');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (375, 'Harold Lorin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (345, 'Harold M. Edwards');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (352, 'Harry Dym');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (659, 'Harry H. Chaudhary.');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (18, 'Harry Henderson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (642, 'Harsha Priya');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (328, 'Harvey E. Rose');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (378, 'Harvey G. Cragon');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (539, 'Harvey M. Deitel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (201, 'Helena Domaine');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (114, 'Henry Garner');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (329, 'Henry Ricardo');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (412, 'Hesham El-Rewini');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (693, 'Hewlett-Packard Company');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (688, 'Hubert S. Howe');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (189, 'Hugh F. Durrant-Whyte');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (363, 'I. M. Gelfand');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (387, 'Ian East');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (163, 'Ian Millington');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (178, 'Ilias G. Maglogiannis');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (50, 'Ioannis Manoussakis');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (705, 'Irving Allen Dodes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (159, 'Ivan Bratko');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (451, 'J. A. Peacock');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (644, 'J. B. Dixit');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (636, 'J. Emmett Beam');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (683, 'J. Michael Bennett');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (431, 'J. Prost');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (441, 'J.M. Cowley');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (58, 'Jack Belzer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (30, 'Jacob T. Schwartz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (660, 'Jacqueline A. Jones');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (20, 'Jake VanderPlas');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (244, 'James David Rockefeller');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (39, 'James G. Williams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (493, 'James Gillies');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (615, 'James Gosling');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (216, 'James L. Fuller');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (183, 'James L. Noyes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (669, 'James L. Peterson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (684, 'James Leiterman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (268, 'James M. Henle');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (264, 'James Stewart');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (682, 'James T. Streib');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (188, 'James Trevelyan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (367, 'James W. Demmel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (23, 'Jaroslav Nešetřil');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (390, 'Jaswinder Pal Singh');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (22, 'Jean-Pierre Gazeau');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (477, 'Jearl Walker');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (479, 'Jed Z. Buchwald');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (421, 'Jeffrey Duntemann');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (142, 'Jeffrey M. Stanton');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (141, 'Jeffrey S. Saltz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (137, 'Jennifer L. Reese');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (43, 'Jeri Freedman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (273, 'Jerrold Marsden');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (169, 'Jerry Kaplan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (88, 'Jiahua Chen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (426, 'Jim Breithaupt');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (481, 'Jim Jardine');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (500, 'Jim Sterne');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (337, 'Jin Ho Kwak');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (639, 'Jitendra Patel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (53, 'Joan Lasenby');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (685, 'Joe Carthy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (86, 'Joel Grus');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (536, 'John A. Vonk');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (466, 'John Avison');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (369, 'John B. Little');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (287, 'John B. Reade');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (224, 'John Baillieul');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (298, 'John C. Peterson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (432, 'John Cardy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (80, 'John Chandler');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (246, 'John Davidson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (280, 'John Frederick Young');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (164, 'John Funge');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (154, 'John Haugeland');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (448, 'John Houghton');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (373, 'John L. Hennessy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (29, 'John Lewis');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (42, 'John M. Zelle');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (379, 'John Patrick Hayes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (125, 'John Paul Mueller');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (259, 'John Stevenson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (44, 'John Walker Gray');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (230, 'John X. Liu');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (370, 'John Y. Hsu');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (697, 'Jon Lindsay');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (131, 'Jose Manuel Magallanes Reyes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (190, 'Joseph A. Angelo');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (386, 'Joseph D. Dumas II');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (214, 'Joseph F. Engelberger');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (522, 'Joseph Hargitai');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (496, 'Joseph T. Wells');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (452, 'Joshi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (257, 'Joshua Welsh');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (597, 'Joy Starks');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (577, 'Joyce Farrell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (670, 'Judi N. Fernández');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (695, 'Julio Sanchez');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (32, 'Justin Zobel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (330, 'K. A. Stroud');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (460, 'K. F. Riley');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (305, 'K.R.Choubey');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (637, 'Kamthane Ashok');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (286, 'Karl J. Smith');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (537, 'Karl L. Erickson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (251, 'Karla Max');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (203, 'Kathy Ceceri');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (512, 'Keiko Pitter');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (226, 'Keith Abney');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (604, 'Keith Duddy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (661, 'Keith Harrow');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (541, 'Kelleigh Wing');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (614, 'Ken Arnold');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (482, 'Ken Stewart');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (638, 'Kenneth Pugh');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (219, 'Kenneth Y. Goldberg');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (179, 'Kevin Warwick');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (156, 'Khateeb M. Hussain');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (687, 'Kip R. Irvine');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (354, 'Klaus Jänich');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (450, 'Kwok K. Ng');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (438, 'L D Landau');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (299, 'L. Corwin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (332, 'L. Mirsky');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (680, 'Lance A. Leventhal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (365, 'Larry Smith');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (126, 'Laura Igual');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (134, 'Laurie Williams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (315, 'Lawrence Corwin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (258, 'Lee Maxwell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (51, 'Leo Dorst');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (464, 'Leopold Infeld');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (353, 'Leslie Hogben');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (445, 'Lev Davidovich Landau');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (447, 'Lev Petrovich Pitaevskiĭ');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (406, 'Lieven Eeckhout');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (71, 'Lillian Pierson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (581, 'Lisa Childers');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (357, 'Lloyd N. Trefethen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (348, 'Lorenzo Robbiano');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (208, 'Lorenzo Sciavicco');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (474, 'Louis J. Battan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (488, 'Louis Rosenfeld');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (123, 'Luca Massaron');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (647, 'Luciano Maria Barone');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (209, 'Luigi Villani');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (67, 'M. P. Fourman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (461, 'M. P. Hobson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (149, 'M. Tim Jones');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (653, 'M.A. Jayaram');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (195, 'Maja J. Matarić');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (103, 'Manfred Mayr');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (236, 'Manuel Braschi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (168, 'Margaret A. Boden');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (458, 'Margaret Dillard Bleick');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (405, 'Mario De Blasi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (380, 'Mark Donald Hill');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (507, 'Mark Fischetti');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (518, 'Mark Kressin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (60, 'Mark Meyer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (478, 'Mark Thomson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (167, 'Matt Ginsberg');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (109, 'Matthew Hallett');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (66, 'Maurice Tchuente');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (360, 'Max Fogiel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (202, 'Michael Brady');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (269, 'Michael C. Gemignani');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (155, 'Michael C. Harris');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (271, 'Michael Comenetz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (520, 'Michael Day');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (238, 'Michael J. Casey');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (376, 'Michael J. Flynn');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (598, 'Michael Mick');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (200, 'Michael Nagenborg');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (148, 'Michael Negnevitsky');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (110, 'Michael R. Brzustowicz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (266, 'Michael Spivak');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (48, 'Michel M. Deza');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (471, 'Michel Peyrard');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (72, 'Mike Loukides');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (633, 'Mike McGrath');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (689, 'Mike Smith');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (247, 'Miles Price');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (469, 'Miriam A. Lazar');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (215, 'Mittal & Nagrath');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (19, 'Mordechai Ben-Ari');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (459, 'Morris H. Shamos');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (275, 'Morris Kline');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (413, 'Mostafa Abd-El-Barr');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (304, 'Mukul Bhatt');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (300, 'Murray H. Protter');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (61, 'N. David Mermin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (484, 'N.G. Van Kampen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (508, 'Nancy J. Yeager');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (319, 'Nancy Jim Poxon');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (662, 'Narain Gehani');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (621, 'Nathan Meyers');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (516, 'National Library of Education (U.S.)');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (54, 'National Research Council');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (686, 'Ned Chapin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (282, 'Neil Gandal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (28, 'Nell Dale');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (501, 'net.Genesis Corporation');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (453, 'Neville H. Fletcher');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (75, 'Nicholas J. Horton');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (191, 'Nicholas Roy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (197, 'Nikos Katevas');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (151, 'Nils J. Nilsson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (377, 'Nirmala Sharma');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (85, 'Norman Matloff');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (381, 'Norman Paul Jouppi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (93, 'Noughabi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (194, 'Oussama Khatib');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (430, 'P. G. de Gennes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (472, 'P. M. Chaikin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (68, 'P. T. Johnstone');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (626, 'P.B. Kotur');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (171, 'PARAG KULKARNI');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (225, 'Patrick Lin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (233, 'Patt Tomas');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (538, 'Paul J. Deitel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (213, 'Paul Kupperberg');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (237, 'Paul Vigna');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (542, 'Paul Whitehead');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (666, 'Penn Brumm');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (341, 'Peter D. Lax');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (525, 'Peter Flynn');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (101, 'Peter Haber');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (605, 'Peter Haggar');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (187, 'Peter I. Corke');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (487, 'Peter Morville');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (278, 'Peter Norvig');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (339, 'Peter Petersen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (635, 'Peter Van der Linden');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (7, 'Philip A. Laplante');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (301, 'Philip E. Protter');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (402, 'Phillip A. Laplante');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (193, 'Pieter Abbeel');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (583, 'Poornachandra Sarang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (172, 'PRACHI JOSHI');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (322, 'Prakash Om');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (113, 'Priti Srinivas Sajja');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (180, 'Professor of Cybernetics Kevin Warwick');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (323, 'R. B. Bapat');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (325, 'R. B. J. T. Allenby');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (494, 'R. Cailliau');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (46, 'R. F. C. Walters');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (643, 'R. Ranjeet');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (388, 'R. W. Doran');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (95, 'Raahemi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (199, 'Rafael Capurro');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (161, 'Rajakishore Nath');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (112, 'Rajendra Akerkar');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (425, 'Rajiv Chopra');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (578, 'Rajiv Sharma');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (649, 'Rakesh Tyata');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (692, 'Ralph Molesworth');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (422, 'Ralph Roberts');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (631, 'Rama Reddy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (296, 'Ramesh Kumar');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (700, 'Randall Hyde');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (303, 'Ravish R Singh');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (532, 'Ray E. Metz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (49, 'Reinhardt Euler');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (443, 'Richard A. Muller');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (668, 'Richard Blum');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (416, 'Richard C. Detmer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (288, 'Richard Courant');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (176, 'Richard Khoury');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (136, 'Richard M. Reese');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (509, 'Robert E. McGrath');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (704, 'Robert Erskine');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (480, 'Robert Fox');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (146, 'Robert Greenberger');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (255, 'Robert H. Deng');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (35, 'Robert Hilton');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (395, 'Robert J. Baron');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (261, 'Robert J. Munro');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (340, 'Robert J. Valenza');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (703, 'Robert L. Stafford');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (513, 'Robert M. Minato');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (356, 'Robert Messer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (675, 'Robert Mottola');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (476, 'Robert Resnick');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (316, 'Robert Szczarba');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (227, 'Robin Murphy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (502, 'Roger W. Morrell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (590, 'Rohit Khurana');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (497, 'Rolf Oppliger');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (14, 'Roman E. Maeder');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (272, 'Ron Larson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (12, 'Roselyn Teukolsky');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (302, 'Ross L. Finney');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (145, 'Roy Freedle');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (242, 'RS Tumber');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (678, 'Rudd');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (92, 'Rushdi Shams');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (212, 'Russel A. Faust');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (671, 'Ruth Ashley');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (174, 'Ryszard S. Michalski');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (295, 'S. C. Arora');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (462, 'S. J. Bence');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (411, 'S.S.Jadhav');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (198, 'Saeed Niku');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (228, 'Saha');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (140, 'Samir Madhavan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (498, 'Samuel Joshua Friedman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (147, 'Sandra Giddens');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (127, 'Santi Seguí');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (396, 'Sarah Harris');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (318, 'Scott M. Farrand');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (232, 'Sean Bennett');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (326, 'Serge Lang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (665, 'Shefali Bansal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (349, 'Sheldon Axler');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (206, 'Shimon Y. Nof');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (320, 'Shirley O. Hockett');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (503, 'Shishir Gundavaram');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (467, 'Shun Lien Chuang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (78, 'Shyi-Ming Chen');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (399, 'Silvia M. Mueller');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (449, 'Simon M. Sze');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (84, 'Sinan Ozdemir');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (677, 'Sivarama P. Dandamudi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (417, 'Smruti Ranjan Sarangi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (444, 'Soshin Chikazumi');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (162, 'Soteris Kalogirou');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (138, 'Srinivas Duvvuri');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (290, 'Stanley I. Grossman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (47, 'Stasys Jukna');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (489, 'Stephanie Sammartino McPherson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (627, 'Stephen G. Kochan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (437, 'Stephen Pople');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (514, 'Stephen Wilson');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (531, 'Steve Browne');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (600, 'Steve Holzner');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (630, 'Steve Oualline');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (312, 'Steven E. Rigdon');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (499, 'Steven J. Vaughan-Nichols');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (611, 'Steven P. Warr');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (342, 'Steven Roman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (143, 'Steven S. Skiena');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (276, 'Steven Strogatz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (277, 'Stuart Russell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (25, 'Subrata Dasgupta');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (410, 'Subrata Ghoshal');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (608, 'Sun-Chong Wang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (338, 'Sungpyo Hong');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (699, 'Susan Bramer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (10, 'Suzie Hamington');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (81, 'Swarna Reddy');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (593, 'Swarnalatha Ashok');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (473, 'T. C. Lubensky');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (657, 'T. D. Brown');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (324, 'T.A. Whitelaw');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (249, 'T.J. Richmond');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (404, 'T.R. Lewin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (606, 'Terrill Brett Spell');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (409, 'Terry J. Fountain');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (385, 'Thea Iberall');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (470, 'Thierry Dauxois');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (596, 'Thomas J. Cashman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (102, 'Thomas Lampoltshammer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (130, 'Thomas Mailund');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (641, 'Thomas Plum');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (217, 'Thomas R. Kurfess');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (454, 'Thomas Rossing');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (694, 'Thomas S. Frank');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (505, 'Thomas Swiss');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (135, 'Thomas Zimmermann');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (506, 'Tim Berners-Lee');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (423, 'Tim Mamtora');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (133, 'Tim Menzies');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (601, 'Timothy Budd');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (6, 'Timothy Colburn');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (83, 'Tom Fawcett');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (529, 'Tom Negrino');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (62, 'Tony Greening');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (222, 'Toshio Fukuda');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (234, 'Travis Goleman');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (223, 'Tsuyoshi Ueyama');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (650, 'Udayakumar G Kulkarni');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (517, 'United States. Office of Educational Research and Improvement');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (419, 'V. M. Milutinovic');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (634, 'V. RAJARAMAN');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (132, 'Valliappa Lakshmanan');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (613, 'Vaskaran Sarcar');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (205, 'Vedran Kordic');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (347, 'Vikas Bist');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (346, 'Vivek Sahai');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (579, 'Vivek Sharma');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (118, 'Vladimir Batagelj');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (515, 'W. David Schwaderer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (679, 'Walter G Rudd');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (696, 'Walter G. Rudd');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (468, 'Walter Lewin');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (333, 'Ward Cheney');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (691, 'Ward Douglas Maurer');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (293, 'Warren S. Wright');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (111, 'Wil M.P. van der Aalst');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (279, 'William B. Gevarter');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (681, 'William B. Giles');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (690, 'William B. Jones');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (663, 'William D. Roome');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (401, 'William F. Gilreath');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (673, 'William Ford');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (260, 'William H. Byrnes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (440, 'William M. Haynes');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (674, 'William R. Topp');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (308, 'William Ritchie');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (77, 'Witold Pedrycz');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (400, 'Wolfgang J. Paul');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (594, 'Xavier');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (89, 'Xuewen Lu');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (609, 'Y. Daniel Liang');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (599, 'Yakov Fain');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (166, 'Yi Du');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (173, 'Yves Kodratoff');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (65, 'Yves Robert');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (456, 'Yvonne Choquet-Bruhat');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (104, 'Zacharias Voulgaris');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (70, 'Zhongwan Lu');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (547, 'А. А. Чекатьков');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (433, 'А. В Кудинов');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (551, 'Абрамкин Г. П.');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (544, 'Авдюхин Андрей Андреевич');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (562, 'Андрей Викторович Столяров');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (651, 'Б±рн Страуструп');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (556, 'Борис Исаевич Зайчик');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (574, 'Бройдо В Л');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (561, 'В. М. Зорин');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (572, 'Вадим Проскурин');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (560, 'Валентин Александрович Григорьев');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (565, 'Виктор Иванович Юров');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (567, 'Даниэль Пак');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (555, 'Евгений Константинович Масловский');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (552, 'Ефремов Ю. С.');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (558, 'Ирина Козлова');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (543, 'Калашников Олег Александрович');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (559, 'Ленинградский политехнический институт имени М.И. Калинина');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (548, 'Надежда Федоровна Богаченко');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (557, 'Нина Сергеевна Скороход');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (434, 'Объединенный институт ядерных исследований (Dubna');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (573, 'Олег Дивов');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (545, 'Пирогов Владислав Юрьевич');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (546, 'Питер Абель');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (550, 'Ревич Юрий Всеволодович');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (554, 'Редакция журнала Секрет Фирмы');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (571, 'Руслан Аблязов');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (549, 'Сара Баазе');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (568, 'Стефан Рэнди Дэвис');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (566, 'Стивен Баррет');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (553, 'Токарева О. В.');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (569, 'Хофманн М.');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (564, 'Эксмо');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (394, 'Эндрю С. Таненбаум');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (563, 'Юрий Магда');
INSERT INTO librarian.lmsinno_author (author_id, name) VALUES (570, '陳盛重');