# Generated by Django 2.0.1 on 2018-01-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default=None, max_length=1000)),
                ('publisher', models.CharField(default=None, max_length=255)),
                ('year', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('price', models.FloatField()),
                ('is_reference', models.BooleanField(default=False)),
                ('copies_available', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsOfAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lmsinno.Author')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lmsinno.Document')),
            ],
            options={
                'db_table': 'lmsinno_documents_of_author',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=32)),
                ('password_salt', models.CharField(default=None, max_length=32)),
                ('role', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
    ]
