# Generated by Django 2.0.1 on 2018-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('price', models.FloatField()),
                ('is_reference', models.BooleanField(default=False)),
                ('copies_available', models.IntegerField()),
            ],
        ),
    ]
