# Generated by Django 2.0.1 on 2018-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='place_hall_number',
            field=models.IntegerField(default=364, unique=True),
        ),
    ]
