# Generated by Django 2.0.1 on 2018-01-22 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinLengthValidator(10000000000), django.core.validators.MaxLengthValidator(99999999999)]),
        ),
    ]
