# Generated by Django 2.0.1 on 2018-02-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_accepted',
            field=models.DateField(default=None, null=True),
        ),
    ]
