# Generated by Django 2.0.1 on 2018-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='innopolis', max_length=100),
        ),
    ]
