# Generated by Django 2.0.1 on 2018-01-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='copies_available',
        ),
    ]
