# Generated by Django 2.0.1 on 2018-01-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0002_remove_document_copies_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default=None, max_length=32)),
                ('password_salt', models.CharField(default=None, max_length=32)),
                ('role', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('first_name', models.CharField(default=None, max_length=20)),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='copies_available',
            field=models.IntegerField(default=0),
        ),
    ]
