# Generated by Django 2.0.1 on 2018-01-22 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0002_auto_20180122_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinLengthValidator(10000000000), django.core.validators.MaxLengthValidator(99999999999)]),
        ),
    ]
