# Generated by Django 2.0.1 on 2018-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0002_auto_20180218_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='place_hall_number',
            field=models.IntegerField(default=513),
        ),
    ]
