# Generated by Django 2.0.1 on 2018-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0003_auto_20180312_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_attach',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.FloatField(choices=[(0.0, 'Basic user'), (1.1, 'Instructor'), (1.2, 'TA'), (1.3, 'VProfessor'), (1.4, 'Professor'), (2.0, 'Librarian')], default=0),
        ),
    ]
