# Generated by Django 2.0.1 on 2018-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0003_auto_20180218_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='place_hall_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='copy',
            name='place_shelf_letter',
            field=models.CharField(max_length=1),
        ),
    ]
