# Generated by Django 2.0.1 on 2018-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0004_auto_20180122_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
