# Generated by Django 2.0.1 on 2018-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0004_auto_20180206_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_return',
            field=models.DateField(default=None, null=True),
        ),
    ]
