# Generated by Django 2.0.1 on 2018-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0004_auto_20180325_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In queue'), (1, 'Booked'), (4, 'Extended'), (2, 'Overdue'), (3, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(100, 'Basic user'), (210, 'Instructor'), (220, 'Teacher Assistant'), (230, 'Visiting Professor'), (240, 'Professor'), (300, 'Librarian')], default=100),
        ),
    ]
