# Generated by Django 2.0.1 on 2018-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0005_auto_20180122_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='authors',
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
