# Generated by Django 2.0.1 on 2018-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0005_auto_20180326_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In queue'), (1, 'Booked'), (2, 'Overdue'), (3, 'Closed')], default=0),
        ),
    ]
