# Generated by Django 2.0.1 on 2018-01-22 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0006_auto_20180123_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('copy_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 0)], default=0)),
                ('place_hall_number', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(9999)])),
                ('place_shelf_letter', models.CharField(default='A', max_length=1)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lmsinno.Document')),
            ],
        ),
    ]
