# Generated by Django 2.0.1 on 2018-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0006_auto_20180326_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.CharField(default='empty', max_length=1255),
        ),
    ]
