# Generated by Django 2.0.1 on 2018-01-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0006_auto_20180122_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsOfAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='documentsofauthor',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lmsinno.Author'),
        ),
        migrations.AddField(
            model_name='documentsofauthor',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lmsinno.Document'),
        ),
    ]
