# Generated by Django 2.0.1 on 2018-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0006_auto_20180207_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Bestseller',
        ),
    ]
