# Generated by Django 2.0.1 on 2018-01-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0008_auto_20180122_1427'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentsofauthor',
            table='documents_of_author',
        ),
    ]
