# Generated by Django 2.0.1 on 2018-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0008_usertelegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegram',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='UserTelegram',
        ),
    ]
