# Generated by Django 2.0.1 on 2018-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0010_auto_20180330_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not ordered'), (1, 'Ordered')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
    ]
