# Generated by Django 2.0.1 on 2018-01-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0010_auto_20180122_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsofauthor',
            name='id',
        ),
        migrations.AlterField(
            model_name='documentsofauthor',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lmsinno.Document'),
        ),
    ]
