# Generated by Django 2.0.3 on 2018-04-23 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0011_auto_20180401_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True)),
                ('method_type', models.IntegerField(choices=[(0, 'GET'), (1, 'PUT'), (2, 'DELETE'), (3, 'POST'), (4, 'UPDATE'), (5, 'PATCH')], default=0)),
                ('log_msg_type', models.IntegerField(choices=[(0, 'INFO'), (1, 'WARNING'), (2, 'ERROR')], default=0)),
                ('description', models.TextField(blank=True)),
                ('params', models.TextField(blank=True)),
                ('response_status', models.CharField(default='No response', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(100, 'Basic user'), (210, 'Instructor'), (220, 'Teacher Assistant'), (230, 'Visiting Professor'), (240, 'Professor'), (300, 'Librarian Base'), (310, 'Librarian 1'), (320, 'Librarian 2'), (330, 'Librarian 3')], default=100),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
