# Generated by Django 2.0.1 on 2018-01-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0011_auto_20180122_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsofauthor',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='documentsofauthor',
            old_name='document_id',
            new_name='document',
        ),
    ]
