# Generated by Django 2.0.1 on 2018-01-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0012_auto_20180122_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsofauthor',
            old_name='document',
            new_name='document_id',
        ),
    ]
