# Generated by Django 2.0.1 on 2018-01-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0013_auto_20180122_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsofauthor',
            old_name='document_id',
            new_name='document',
        ),
    ]
