# Generated by Django 2.0.1 on 2018-01-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0014_auto_20180123_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='document',
            new_name='documentsss',
        ),
    ]
