# Generated by Django 2.0.1 on 2018-01-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0015_auto_20180123_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='documentsss',
            new_name='documentsss_id',
        ),
    ]
