# Generated by Django 2.0.1 on 2018-01-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0016_auto_20180123_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestseller',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='documentsss_id',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='documentofauthor',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='documentofauthor',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tagofdocument',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='tagofdocument',
            old_name='tag',
            new_name='tag_id',
        ),
    ]
