# Generated by Django 2.0.1 on 2018-01-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0017_auto_20180123_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestseller',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='documentofauthor',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='documentofauthor',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tagofdocument',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='tagofdocument',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
