# Generated by Django 2.0.1 on 2018-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0018_auto_20180123_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_accepted',
            field=models.DateField(),
        ),
    ]
