# Generated by Django 2.0.1 on 2018-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0019_auto_20180123_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_accepted',
            field=models.DateField(default=None),
        ),
    ]
