# Generated by Django 2.0.1 on 2018-01-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0021_auto_20180123_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagofdocument',
            table='tag_of_document',
        ),
    ]
