# Generated by Django 2.0.1 on 2018-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0022_auto_20180123_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, max_length=1),
        ),
    ]
