# Generated by Django 2.0.1 on 2018-01-23 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0025_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
