# Generated by Django 2.0.1 on 2018-01-23 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0031_auto_20180123_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
