# Generated by Django 2.0.1 on 2018-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0033_auto_20180123_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='place_hall_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
