# Generated by Django 2.0.1 on 2018-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0034_auto_20180123_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
