# Generated by Django 2.0.1 on 2018-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0035_auto_20180123_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'Book'), (1, 'Journal article'), (2, 'AV')], default=0),
        ),
    ]
