# Generated by Django 2.0.1 on 2018-01-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0036_auto_20180123_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In queue'), (1, 'Booked'), (2, 'Overdue'), (3, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Basic user'), (1, 'Faculty'), (2, 'Librarian')], default=0),
        ),
    ]
