# Generated by Django 2.0.1 on 2018-01-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0037_auto_20180123_2203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tagofdocument',
            table='lmsinno_tag_of_document',
        ),
    ]
