# Generated by Django 2.0.1 on 2018-01-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0038_auto_20180123_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=models.CharField(max_length=255)),
        ),
    ]
