# Generated by Django 2.0.1 on 2018-01-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0039_auto_20180124_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, unique=True),
        ),
    ]
