# Generated by Django 2.0.1 on 2018-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0041_auto_20180124_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2018, max_digits=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, unique=True),
        ),
    ]
