# Generated by Django 2.0.1 on 2018-01-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0042_auto_20180124_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.FilePathField(default='../covers_for_documents/empty.jpg'),
        ),
    ]
