# Generated by Django 2.0.1 on 2018-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0043_user_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover',
        ),
        migrations.AddField(
            model_name='document',
            name='cover',
            field=models.FilePathField(default='../covers_for_documents/empty.jpg'),
        ),
    ]
