# Generated by Django 2.0.1 on 2018-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0044_auto_20180127_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.FilePathField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 'Book'), (1, 'Journal article'), (2, 'AV')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
