# Generated by Django 2.0.1 on 2018-01-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0046_auto_20180128_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.FilePathField(default='empty', max_length=255),
        ),
    ]
