# Generated by Django 2.0.1 on 2018-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0047_auto_20180128_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover',
            field=models.CharField(default='empty', max_length=255),
        ),
    ]
