# Generated by Django 2.0.1 on 2018-02-05 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lmsinno', '0048_auto_20180128_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
