import requests

# Users types
BASIC_USER_ROLE = 100
INSTRUCTOR_ROLE = 210
TEACHER_ASSISTANT_ROLE = 220
VISITING_PROFESSOR_ROLE = 230
PROFESSOR_ROLE = 240
LIBRARIAN_BASE_ROLE = 300
LIBRARIAN1_ROLE = 310
LIBRARIAN2_ROLE = 320
LIBRARIAN3_ROLE = 330

LIBRARIAN_ROLE_LIST = [LIBRARIAN_BASE_ROLE, LIBRARIAN1_ROLE, LIBRARIAN2_ROLE, LIBRARIAN3_ROLE]

# Document types
BOOK_TYPE = 0
JOURNAL_TYPE = 1
AV_TYPE = 2

# Order status
IN_QUEUE_STATUS = 0
BOOKED_STATUS = 1
OVERDUE_STATUS = 2
CLOSED_STATUS = 3

# Copy status
NOT_ORDERED_STATUS = 0
ORDERED_STATUS = 1

# Sum for one day of overdue
OVERDUE_CONST = 100

# Telegram Bot Token
BOT_KEY = '566111170:AAG1yAUuZEbQQbhHovQTiqzuzzVrwjj8ALg'

# HTTPS Connection
HTTP_SESSION = requests.Session()

# HTTP Method Type
GET = 0
PUT = 1
DELETE = 2
POST = 3
UPDATE = 4
PATCH = 5

# Log message type
INFO = 0
WARNING = 1
ERROR = 2
