get_doc_by_criteria = 'GET documents by criteria by user ({0}:{1})'
get_doc_by_id = 'GET document by ID by user ({0}:{1})'
post_doc = 'POST(Adding) document by user ({0}:{1})'
delete_doc_by_id = 'DELETE document by ID by user ({0}:{1})'
patch_doc_by_id = 'PATCH document by ID by user ({0}:{1})'
get_doc_by_copy_id = 'GET document by Copy ID by user ({0}:{1})'
get_bestsellers = 'GET bestsellers by user ({0}:{1})'
